# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exp.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_exp(object):
    def setupUi(self, Form_exp):
        Form_exp.setObjectName("Form_exp")
        Form_exp.resize(553, 620)
        self.groupBox_3 = QtWidgets.QGroupBox(Form_exp)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 244, 531, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 20, 511, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(55, 28))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.lineEdit_cmd = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_cmd.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEdit_cmd.setObjectName("lineEdit_cmd")
        self.horizontalLayout_8.addWidget(self.lineEdit_cmd)
        self.pushButton_cmd = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_cmd.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_cmd.setObjectName("pushButton_cmd")
        self.horizontalLayout_8.addWidget(self.pushButton_cmd)
        self.groupBox_2 = QtWidgets.QGroupBox(Form_exp)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 310, 531, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 511, 41))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_4.setMinimumSize(QtCore.QSize(55, 28))
        self.label_4.setMaximumSize(QtCore.QSize(55, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEdit_ip = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_ip.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEdit_ip.setMaximumSize(QtCore.QSize(500, 16777215))
        self.lineEdit_ip.setText("")
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.horizontalLayout_2.addWidget(self.lineEdit_ip)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_5.setMinimumSize(QtCore.QSize(0, 28))
        self.label_5.setMaximumSize(QtCore.QSize(32, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineEdit_port = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_port.setMinimumSize(QtCore.QSize(50, 28))
        self.lineEdit_port.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_port.setText("")
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.horizontalLayout_2.addWidget(self.lineEdit_port)
        self.comboBox_type = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_type.setMinimumSize(QtCore.QSize(87, 28))
        self.comboBox_type.setMaximumSize(QtCore.QSize(110, 28))
        self.comboBox_type.setObjectName("comboBox_type")
        self.horizontalLayout_2.addWidget(self.comboBox_type)
        self.pushButton_shell = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_shell.setObjectName("pushButton_shell")
        self.horizontalLayout_2.addWidget(self.pushButton_shell)
        self.groupBox = QtWidgets.QGroupBox(Form_exp)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 531, 229))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 25, 511, 73))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.layoutWidget_3)
        self.label.setMinimumSize(QtCore.QSize(55, 20))
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.lineEdit_url = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_url.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEdit_url.setSizeIncrement(QtCore.QSize(0, 0))
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.horizontalLayout_4.addWidget(self.lineEdit_url)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_2.setMinimumSize(QtCore.QSize(55, 20))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_cookie = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_cookie.setMinimumSize(QtCore.QSize(0, 28))
        self.lineEdit_cookie.setObjectName("lineEdit_cookie")
        self.horizontalLayout_3.addWidget(self.lineEdit_cookie)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 55, 28))
        self.label_6.setMinimumSize(QtCore.QSize(55, 28))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_6.setObjectName("label_6")
        self.textEdit_heads = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_heads.setGeometry(QtCore.QRect(10, 130, 511, 87))
        self.textEdit_heads.setObjectName("textEdit_heads")
        self.groupBox_4 = QtWidgets.QGroupBox(Form_exp)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 380, 531, 231))
        self.groupBox_4.setObjectName("groupBox_4")
        self.textEdit_result = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit_result.setGeometry(QtCore.QRect(10, 20, 511, 201))
        self.textEdit_result.setObjectName("textEdit_result")

        self.retranslateUi(Form_exp)
        QtCore.QMetaObject.connectSlotsByName(Form_exp)

    def retranslateUi(self, Form_exp):
        _translate = QtCore.QCoreApplication.translate
        Form_exp.setWindowTitle(_translate("Form_exp", "一键利用"))
        self.groupBox_3.setTitle(_translate("Form_exp", "命令执行"))
        self.label_9.setText(_translate("Form_exp", "Cmd命令"))
        self.lineEdit_cmd.setText(_translate("Form_exp", "whoami"))
        self.pushButton_cmd.setText(_translate("Form_exp", "执行命令"))
        self.groupBox_2.setTitle(_translate("Form_exp", "反弹Shell"))
        self.label_4.setText(_translate("Form_exp", "IP地址:"))
        self.label_5.setText(_translate("Form_exp", "Port"))
        self.pushButton_shell.setText(_translate("Form_exp", "反弹shell"))
        self.groupBox.setTitle(_translate("Form_exp", "命令执行"))
        self.label.setText(_translate("Form_exp", "URL地址"))
        self.label_2.setText(_translate("Form_exp", "Cookie"))
        self.label_6.setText(_translate("Form_exp", "heads"))
        self.textEdit_heads.setHtml(_translate("Form_exp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji\'; color:#212529; background-color:#ffffff;\">User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36</span></p></body></html>"))
        self.groupBox_4.setTitle(_translate("Form_exp", "Result"))
        self.textEdit_result.setHtml(_translate("Form_exp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">命令执行的结果将会显示在这里。</p></body></html>"))

