# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Plugins_information.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Plugins_information(object):
    def setupUi(self, Plugins_information):
        Plugins_information.setObjectName("Plugins_information")
        Plugins_information.resize(660, 451)
        self.gridLayout = QtWidgets.QGridLayout(Plugins_information)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Plugins_information)
        self.label_2.setMinimumSize(QtCore.QSize(70, 35))
        self.label_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.vuln_name = QtWidgets.QLabel(Plugins_information)
        self.vuln_name.setText("")
        self.vuln_name.setObjectName("vuln_name")
        self.horizontalLayout_2.addWidget(self.vuln_name)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(Plugins_information)
        self.label_4.setMinimumSize(QtCore.QSize(70, 32))
        self.label_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.vuln_url = QtWidgets.QLabel(Plugins_information)
        self.vuln_url.setText("")
        self.vuln_url.setOpenExternalLinks(True)
        self.vuln_url.setObjectName("vuln_url")
        self.horizontalLayout_5.addWidget(self.vuln_url)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Plugins_information)
        self.label_3.setMaximumSize(QtCore.QSize(40, 30))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.vuln_poc = QtWidgets.QLabel(Plugins_information)
        self.vuln_poc.setObjectName("vuln_poc")
        self.horizontalLayout_3.addWidget(self.vuln_poc)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(Plugins_information)
        self.label_11.setMaximumSize(QtCore.QSize(40, 30))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.vuln_exp = QtWidgets.QLabel(Plugins_information)
        self.vuln_exp.setObjectName("vuln_exp")
        self.horizontalLayout_9.addWidget(self.vuln_exp)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(Plugins_information)
        self.label_6.setMinimumSize(QtCore.QSize(70, 32))
        self.label_6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.vuln_file = QtWidgets.QLabel(Plugins_information)
        self.vuln_file.setText("")
        self.vuln_file.setObjectName("vuln_file")
        self.horizontalLayout_4.addWidget(self.vuln_file)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Plugins_information)
        self.label.setMinimumSize(QtCore.QSize(70, 35))
        self.label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cms_name = QtWidgets.QLabel(Plugins_information)
        self.cms_name.setText("")
        self.cms_name.setObjectName("cms_name")
        self.horizontalLayout.addWidget(self.cms_name)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(Plugins_information)
        self.label_8.setMinimumSize(QtCore.QSize(70, 32))
        self.label_8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.vuln_identifier = QtWidgets.QLabel(Plugins_information)
        self.vuln_identifier.setText("")
        self.vuln_identifier.setObjectName("vuln_identifier")
        self.horizontalLayout_7.addWidget(self.vuln_identifier)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(Plugins_information)
        self.label_5.setMinimumSize(QtCore.QSize(60, 32))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.vuln_miaoshu = QtWidgets.QTextEdit(Plugins_information)
        self.vuln_miaoshu.setMinimumSize(QtCore.QSize(0, 0))
        self.vuln_miaoshu.setReadOnly(False)
        self.vuln_miaoshu.setObjectName("vuln_miaoshu")
        self.verticalLayout_2.addWidget(self.vuln_miaoshu)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_13 = QtWidgets.QLabel(Plugins_information)
        self.label_13.setMinimumSize(QtCore.QSize(60, 32))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.vuln_solution = QtWidgets.QTextEdit(Plugins_information)
        self.vuln_solution.setMinimumSize(QtCore.QSize(0, 0))
        self.vuln_solution.setReadOnly(False)
        self.vuln_solution.setObjectName("vuln_solution")
        self.verticalLayout_3.addWidget(self.vuln_solution)
        self.horizontalLayout_11.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Plugins_information)
        QtCore.QMetaObject.connectSlotsByName(Plugins_information)

    def retranslateUi(self, Plugins_information):
        _translate = QtCore.QCoreApplication.translate
        Plugins_information.setWindowTitle(_translate("Plugins_information", "插件详细信息"))
        self.label_2.setText(_translate("Plugins_information", "漏洞名称:"))
        self.label_4.setText(_translate("Plugins_information", "漏洞链接:"))
        self.label_3.setText(_translate("Plugins_information", "POC:"))
        self.vuln_poc.setText(_translate("Plugins_information", "无"))
        self.label_11.setText(_translate("Plugins_information", "EXP:"))
        self.vuln_exp.setText(_translate("Plugins_information", "无"))
        self.label_6.setText(_translate("Plugins_information", "插件位置:"))
        self.label.setText(_translate("Plugins_information", "CMS名称:"))
        self.label_8.setText(_translate("Plugins_information", "漏洞编号:"))
        self.label_5.setText(_translate("Plugins_information", "详细描述"))
        self.vuln_miaoshu.setHtml(_translate("Plugins_information", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_13.setText(_translate("Plugins_information", "修复建议"))
        self.vuln_solution.setHtml(_translate("Plugins_information", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))

