# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Plugins_information.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Plugins_information(object):
    def setupUi(self, Plugins_information):
        Plugins_information.setObjectName("Plugins_information")
        Plugins_information.resize(529, 510)
        self.layoutWidget = QtWidgets.QWidget(Plugins_information)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 250, 471, 233))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(60, 32))
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.vuln_miaoshu = QtWidgets.QTextEdit(self.layoutWidget)
        self.vuln_miaoshu.setMinimumSize(QtCore.QSize(0, 0))
        self.vuln_miaoshu.setReadOnly(True)
        self.vuln_miaoshu.setObjectName("vuln_miaoshu")
        self.verticalLayout.addWidget(self.vuln_miaoshu)
        self.layoutWidget1 = QtWidgets.QWidget(Plugins_information)
        self.layoutWidget1.setGeometry(QtCore.QRect(29, 32, 471, 206))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setMinimumSize(QtCore.QSize(70, 35))
        self.label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cms_name = QtWidgets.QLabel(self.layoutWidget1)
        self.cms_name.setText("")
        self.cms_name.setObjectName("cms_name")
        self.horizontalLayout.addWidget(self.cms_name)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setMinimumSize(QtCore.QSize(70, 35))
        self.label_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.vuln_name = QtWidgets.QLabel(self.layoutWidget1)
        self.vuln_name.setText("")
        self.vuln_name.setObjectName("vuln_name")
        self.horizontalLayout_2.addWidget(self.vuln_name)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setMinimumSize(QtCore.QSize(70, 32))
        self.label_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.plugins_methods = QtWidgets.QLabel(self.layoutWidget1)
        self.plugins_methods.setText("")
        self.plugins_methods.setObjectName("plugins_methods")
        self.horizontalLayout_3.addWidget(self.plugins_methods)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setMinimumSize(QtCore.QSize(70, 32))
        self.label_6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.file_path = QtWidgets.QLabel(self.layoutWidget1)
        self.file_path.setText("")
        self.file_path.setObjectName("file_path")
        self.horizontalLayout_4.addWidget(self.file_path)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setMinimumSize(QtCore.QSize(70, 32))
        self.label_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.vuln_url = QtWidgets.QLabel(self.layoutWidget1)
        self.vuln_url.setText("")
        self.vuln_url.setOpenExternalLinks(True)
        self.vuln_url.setObjectName("vuln_url")
        self.horizontalLayout_5.addWidget(self.vuln_url)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Plugins_information)
        QtCore.QMetaObject.connectSlotsByName(Plugins_information)

    def retranslateUi(self, Plugins_information):
        _translate = QtCore.QCoreApplication.translate
        Plugins_information.setWindowTitle(_translate("Plugins_information", "插件详细信息"))
        self.label_5.setText(_translate("Plugins_information", "详细描述"))
        self.vuln_miaoshu.setHtml(_translate("Plugins_information", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("Plugins_information", "CMS名称:"))
        self.label_2.setText(_translate("Plugins_information", "漏洞名称:"))
        self.label_3.setText(_translate("Plugins_information", "插件方法:"))
        self.label_6.setText(_translate("Plugins_information", "文件位置:"))
        self.label_4.setText(_translate("Plugins_information", "漏洞链接:"))

