# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Server.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Server(object):
    def setupUi(self, Server):
        Server.setObjectName("Server")
        Server.resize(359, 189)
        self.gridLayout = QtWidgets.QGridLayout(Server)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_server = QtWidgets.QLabel(Server)
        self.label_server.setObjectName("label_server")
        self.horizontalLayout.addWidget(self.label_server)
        self.lineEdit_server = QtWidgets.QLineEdit(Server)
        self.lineEdit_server.setObjectName("lineEdit_server")
        self.horizontalLayout.addWidget(self.lineEdit_server)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_user = QtWidgets.QLabel(Server)
        self.label_user.setObjectName("label_user")
        self.horizontalLayout_2.addWidget(self.label_user)
        self.lineEdit_user = QtWidgets.QLineEdit(Server)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.horizontalLayout_2.addWidget(self.lineEdit_user)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_passwd = QtWidgets.QLabel(Server)
        self.label_passwd.setObjectName("label_passwd")
        self.horizontalLayout_3.addWidget(self.label_passwd)
        self.lineEdit_passwd = QtWidgets.QLineEdit(Server)
        self.lineEdit_passwd.setObjectName("lineEdit_passwd")
        self.horizontalLayout_3.addWidget(self.lineEdit_passwd)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 3)
        self.pushButton_ceshi = QtWidgets.QPushButton(Server)
        self.pushButton_ceshi.setObjectName("pushButton_ceshi")
        self.gridLayout.addWidget(self.pushButton_ceshi, 3, 0, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(Server)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 3, 1, 1, 1)
        self.pushButton_exit = QtWidgets.QPushButton(Server)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.gridLayout.addWidget(self.pushButton_exit, 3, 2, 1, 1)

        self.retranslateUi(Server)
        self.pushButton_exit.clicked.connect(Server.close)
        QtCore.QMetaObject.connectSlotsByName(Server)

    def retranslateUi(self, Server):
        _translate = QtCore.QCoreApplication.translate
        Server.setWindowTitle(_translate("Server", "Server"))
        self.label_server.setText(_translate("Server", "服务器："))
        self.lineEdit_server.setText(_translate("Server", "http://127.0.0.1:8088/"))
        self.label_user.setText(_translate("Server", "用户名："))
        self.lineEdit_user.setText(_translate("Server", "admin"))
        self.label_passwd.setText(_translate("Server", "密  码："))
        self.lineEdit_passwd.setText(_translate("Server", "admin"))
        self.pushButton_ceshi.setText(_translate("Server", "测试连接"))
        self.pushButton_save.setText(_translate("Server", "保存"))
        self.pushButton_exit.setText(_translate("Server", "取消"))
