# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showPlugins.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1459, 821)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/main.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("")
        Form.setInputMethodHints(QtCore.Qt.ImhNone)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.show_Plugins_comboBox_cms_name = QtWidgets.QComboBox(Form)
        self.show_Plugins_comboBox_cms_name.setMinimumSize(QtCore.QSize(150, 0))
        self.show_Plugins_comboBox_cms_name.setStyleSheet("")
        self.show_Plugins_comboBox_cms_name.setEditable(True)
        self.show_Plugins_comboBox_cms_name.setObjectName("show_Plugins_comboBox_cms_name")
        self.show_Plugins_comboBox_cms_name.addItem("")
        self.horizontalLayout.addWidget(self.show_Plugins_comboBox_cms_name)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.show_Plugins_comboBox_vuln_class = QtWidgets.QComboBox(Form)
        self.show_Plugins_comboBox_vuln_class.setMinimumSize(QtCore.QSize(150, 0))
        self.show_Plugins_comboBox_vuln_class.setStyleSheet("")
        self.show_Plugins_comboBox_vuln_class.setEditable(True)
        self.show_Plugins_comboBox_vuln_class.setObjectName("show_Plugins_comboBox_vuln_class")
        self.show_Plugins_comboBox_vuln_class.addItem("")
        self.horizontalLayout.addWidget(self.show_Plugins_comboBox_vuln_class)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.show_Plugins = QtWidgets.QTableWidget(Form)
        self.show_Plugins.setMinimumSize(QtCore.QSize(200, 0))
        self.show_Plugins.setSizeIncrement(QtCore.QSize(0, 0))
        self.show_Plugins.setTabletTracking(False)
        self.show_Plugins.setToolTip("")
        self.show_Plugins.setStatusTip("")
        self.show_Plugins.setAutoFillBackground(False)
        self.show_Plugins.setStyleSheet("")
        self.show_Plugins.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.show_Plugins.setShowGrid(True)
        self.show_Plugins.setGridStyle(QtCore.Qt.SolidLine)
        self.show_Plugins.setWordWrap(True)
        self.show_Plugins.setCornerButtonEnabled(True)
        self.show_Plugins.setObjectName("show_Plugins")
        self.show_Plugins.setColumnCount(10)
        self.show_Plugins.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.show_Plugins.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.show_Plugins.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.show_Plugins.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.show_Plugins.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.show_Plugins.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.show_Plugins.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.show_Plugins.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.show_Plugins.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.show_Plugins.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.show_Plugins.setHorizontalHeaderItem(9, item)
        self.show_Plugins.horizontalHeader().setVisible(True)
        self.show_Plugins.horizontalHeader().setCascadingSectionResizes(True)
        self.show_Plugins.horizontalHeader().setDefaultSectionSize(200)
        self.show_Plugins.horizontalHeader().setHighlightSections(False)
        self.show_Plugins.horizontalHeader().setSortIndicatorShown(True)
        self.show_Plugins.horizontalHeader().setStretchLastSection(True)
        self.show_Plugins.verticalHeader().setVisible(False)
        self.show_Plugins.verticalHeader().setCascadingSectionResizes(False)
        self.show_Plugins.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.show_Plugins)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Show Plugins"))
        self.label.setText(_translate("Form", "应用名称"))
        self.show_Plugins_comboBox_cms_name.setItemText(0, _translate("Form", "ALL"))
        self.label_2.setText(_translate("Form", "漏洞类型"))
        self.show_Plugins_comboBox_vuln_class.setItemText(0, _translate("Form", "ALL"))
        self.show_Plugins.setSortingEnabled(True)
        item = self.show_Plugins.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.show_Plugins.horizontalHeaderItem(1)
        item.setText(_translate("Form", "应用名称"))
        item = self.show_Plugins.horizontalHeaderItem(2)
        item.setText(_translate("Form", "漏洞名称"))
        item = self.show_Plugins.horizontalHeaderItem(3)
        item.setText(_translate("Form", "漏洞类型"))
        item = self.show_Plugins.horizontalHeaderItem(4)
        item.setText(_translate("Form", "漏洞编号"))
        item = self.show_Plugins.horizontalHeaderItem(5)
        item.setText(_translate("Form", "漏洞来源"))
        item = self.show_Plugins.horizontalHeaderItem(6)
        item.setText(_translate("Form", "漏洞描述"))
        item = self.show_Plugins.horizontalHeaderItem(7)
        item.setText(_translate("Form", "插件路径"))
        item = self.show_Plugins.horizontalHeaderItem(8)
        item.setText(_translate("Form", "插件作者"))
        item = self.show_Plugins.horizontalHeaderItem(9)
        item.setText(_translate("Form", "修复建议"))

